// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANjJ9N1Yn_4CA5LXR-nVApvbNpKKjqA4E',
    appId: '1:669709579751:web:d16acea40c98024ff5b942',
    messagingSenderId: '669709579751',
    projectId: 'scanme-d70c9',
    authDomain: 'scanme-d70c9.firebaseapp.com',
    storageBucket: 'scanme-d70c9.firebasestorage.app',
    measurementId: 'G-TB4VE9GCLT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0drBV-UXdeH4vgvz8CDZSGlRGxkf2eW8',
    appId: '1:669709579751:android:7df30c686afa7fe9f5b942',
    messagingSenderId: '669709579751',
    projectId: 'scanme-d70c9',
    storageBucket: 'scanme-d70c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAec81J7lajIgqcaAKy4ERzK3P-j4NCjoU',
    appId: '1:669709579751:ios:ef820db252ba5c07f5b942',
    messagingSenderId: '669709579751',
    projectId: 'scanme-d70c9',
    storageBucket: 'scanme-d70c9.firebasestorage.app',
    iosBundleId: 'com.scanme.app.scanmeApp',
  );
}
